# Generated by Django 5.2.3 on 2025-07-21 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=70)),
                ('To', models.CharField(max_length=70)),
                ('Title', models.CharField(max_length=70)),
                ('Subject', models.TextField()),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Img', models.ImageField(upload_to='Photos/Classes_IMG/%y/%m/%d')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=700)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.class')),
            ],
        ),
        migrations.CreateModel(
            name='C_P_real',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.class')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.class')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.class')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prvard_id', models.CharField(max_length=20)),
                ('Theme', models.CharField(max_length=30)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Points', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='Photos/Students_Profiles_Photos/%y/%m/%d')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.university')),
            ],
        ),
        migrations.CreateModel(
            name='P_U_real',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.university')),
            ],
        ),
        migrations.CreateModel(
            name='C_U_real',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.class')),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.university')),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Markdown', models.TextField()),
                ('Content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvard_main.content')),
            ],
        ),
    ]
