# Generated by Django 5.2.3 on 2025-07-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prvard_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='University',
        ),
    ]
