# Generated by Django 5.2.3 on 2025-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvard_main', '0002_remove_student_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Prvard_id',
            field=models.CharField(max_length=30),
        ),
    ]
