# Generated by Django 5.2.3 on 2025-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvard_main', '0003_alter_university_prvard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_message',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
