# Generated by Django 5.2.3 on 2025-07-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvard_main', '0004_e_message_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_message',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
