# Generated by Django 5.2.3 on 2025-07-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prvard_main', '0005_e_message_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Img',
        ),
    ]
