# Generated by Django 5.2.3 on 2025-08-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvard_main', '0006_remove_class_description_remove_class_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
