# Generated by Django 5.2.3 on 2025-08-05 07:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prvard_main', '0007_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
